cxx_binary(
  name = 'imagecmp',
  srcs = [
    ('imagecmp.cpp', ['-std=c++17']),
    ('./third-party/md5/md5.cpp', ['-std=c++17']),
 ],
)

cxx_test(
  name = 'imagecmp_test',
  srcs = [
    ('imagecmp_test.cpp', ['-g', '-std=c++17']),
  ],
  include_directories = [
    './third-party/gtest/googletest/googletest/include/gtest',
  ],
)
